import { gql } from '@apollo/client';

const LISTING = gql`
  query {
    nodeQuery(limit: 10, offset: 0, filter: {conditions: [{operator: EQUAL, field: "type", value: ["listing"]}]}) {
      entities {
       ... on NodeListing{
            nid
            title
            fieldTaglingL
            fieldCountryL{
              entity{
                tid
                name
              }
            }
            fieldCityL{
              entity{
                tid
                name
              }
            }
            fieldMainImageDesktopL1{
              entity{
                fid
                url
              }
            }
            fieldMainImageMobileL1{
              entity{
                fid
                url
              }
            }
            fieldGalleryDesktopL1{
              entity{
                fid
                url
              }
            }
            fieldGalleryMobileL1{
              entity{
                fid
                url
              }
            }
            fieldBrochureL1{
              entity{
                fid
                url
              }
            }
            fieldProject{
              entity{
                nid
                title
              }
            }
            fieldPrice
            fieldUnitType{
              entity{
                tid
                name
              }
            }
            fieldBedrooms
            fieldBathrooms
            fieldMaidroom
            fieldAreaL1
            fieldLocalityL1
            fieldStatusL1
            fieldReferenceNumber
            fieldCol1ImageDesktopL1{
              entity{
                fid
                url
              }
            }
            fieldCol1ImageMobileL1{
              entity{
                fid
                url
              }
            }
            fieldCol2Row1Col1ImageDesL{
              entity{
                fid
                url
              }
            }
            fieldCol2Row1Col1ImageMobL{
              entity{
                fid
                url
              }
            }
            fieldCol2Row1Col2ImageDesL{
              entity{
                fid
                url
              }
            }
            fieldCol2Row1Col2ImageMobL{
              entity{
                fid
                url
              }
            }
            fieldCol2Row2ImageDesktopL1{
              entity{
                fid
                url
              }
            }
            fieldCol2Row2ImageMobileL1{
              entity{
                fid
                url
              }
            }
            fieldCol1TextL1
            fieldAmenitiesL{
              entity{
                  ... on ParagraphMultipleAmenities{
                      id
                      fieldIcona{url}
                      fieldTextAmi
                      fieldValueAmi
                  }
              }
            }
            fieldDescriptionTextL
            fieldGalleryDesktopL{
              entity{
                fid
                url
              }
            }
            fieldGalleryMobileL{
              entity{
                fid
                url
              }
            }
            fieldAboutTextL{
              value
            }
            fieldVideoL{
              title
              url {
                path
                routed
              }
            }
            fieldLocatorsL{
              entity{
                ... on ParagraphMultipleLocators{
                  id
                  fieldIconm{url}
                  fieldTextc6
                  fieldValuec6
                }
              }
            }
            fieldLatitudeL
            fieldLongitudeL
        }
      }
    }
  }`;

export { LISTING };
