const BATHROOMDATA = [
'3 Bathrooms - 1 ensuite, 2 shared',
'1 shared',
'4 Bathrooms - 3 ensuite, 1 shared',
'2 Bathrooms - 1 ensuite, 1 shared',
'3 Bathrooms - 2 ensuite, 1 shared',
'6 Bathrooms - 5 ensuite, 1 shared',
'4 Bathrooms - 2 ensuite, 2 shared',
'Work in Progress',
'1 Bathroom -  1 ensuite',
'1 Bathroom - 1 ensuite',
'7 Bathrooms - 4 ensuite, 3 shared',
'5 Bathrooms - 3 ensuite, 2 shared',
'9 Bathrooms - 7 ensuite, 2 shared',
'2 (1 en suit bathroom in the masterbedroom, 1 common washroom without bath)',
'2 Bathrooms - 1 ensuit, 1 shared',
'5 Bathrooms - 2 ensuite, 3 shared',
'2 Bathrooms -1 ensuite, 1 shared',
'2 Bathrooms - 2 ensuite',
'1 Bathroom - 1 ensuite, 1 shared',
'6 Bathrooms - 4 ensuite, 2 shared',
'2 Bathrooms - 1 ensuite',
'5 Bathrooms - 3 ensuites, 2 shared',
'2 Bathrooms - 1 ensuite,1 shared',
'1 Bathroom  - 1 ensuite, 1 shared',
'4 Bathrooms -  3 ensuite, 1 shared',
'6',
'2 Bathroons - 1 ensuite, 1 shared',
'1 Bathrooms - 1 ensuite',
'2 Bathrooms- 1 ensuite, 1 shared',
];

export {BATHROOMDATA};